Add zuora.revenue connector
ballerina-platform/openapi-connectors pull request #555
Opened 2021-11-16 03:27 UTC by SanduDS

# Description
This is the ballerina connector for Zuora Revenue API. it provides operations on BI views, reports, jobs etc.

Fixes # (https://github.com/ballerina-platform/ballerina-extended-library/issues/149)
Fixes https://github.com/ballerina-platform/ballerina-openapi/issues/482

One line release note: 
- Ballerina connector for Zoura Revenue API

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
**Test Configuration**:
* Ballerina Version: Ballerina Swan Lake Beta3
* Operating System: Ubuntu 
* Java SDK: Java 11

# Checklist:

### Changes to OpenAPI definition

- [x] Modified `info` section of the OpenAPI definition file - [Example](https://github.com/ballerina-platform/ballerina-extended-library/discussions/74)

    - `description` - what the connector is about 
    - `x-ballerina-init-description` OpenAPI extension - connector initialization details 
    - `x-ballerina-display` OpenAPI extension - connector name and path to the connector icon 

- [x] Added proper description each API Key, if API Key authentication is defined in OpenAPI definition file 

### Changes to connector module

- [x] Added license header at the top of each .bal file. 
- [x] Added Package.md as per the guide [here](https://github.com/ballerina-platform/ballerina-extended-library/discussions/77)
- [x] Added Module.md for the module of the  connector as per the guide [here](https://github.com/ballerina-platform/ballerina-extended-library/discussions/78)
- [ ] Created a directory called `resources` at the root of the connector and copied the connector icon there. 
      Name of the icon file need to be `<connector-name>.svg`
- [x] Added Ballerina.toml file with following information. For keywords refer to [guide](https://github.com/ballerina-platform/ballerina-extended-library/discussions/72)

### Verifying connector module

- [x] Compiled the connector successfully with the targeted ballerina version. 
- [ ] Conducted smoke tests on the connector (Recommended when OpenAPI definition is obtain from an unofficial source)

### Security checks
 - [x] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? 
 - [x] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

2021-11-29 10:13 UTC, aneeshafedo commented on openapi/zuora.revenue/openapi.yml
> +        '200':
We have an open [issue in openapi-tool ](https://github.com/ballerina-platform/openapi-tools/issues/696)side to address this scenario where either of `200` and `204` responses are expected. Current code generation does not support this scenario.

2021-12-08 05:22 UTC, sachinira requested changes

2021-12-08 05:22 UTC, sachinira commented on openapi/zuora.revenue/Ballerina.toml
> +license= ["Apache-2.0"]
Please add the icon definition

2021-12-08 10:56 UTC, aneeshafedo approved these changes

2021-12-08 11:35 UTC, sachinira approved these changes

2021-12-08 11:36 UTC, merged